classDiagram
class MealsApp
MealsApp : +build() Widget
StatelessWidget <|-- MealsApp

class Category
Category : +id String
Category : +title String
Category : +color Color
Category o-- Color

class Meal
Meal : +id String
Meal : +categories List~String~
Meal : +title String
Meal : +imageUrl String
Meal : +ingredients List~String~
Meal : +steps List~String~
Meal : +duration int
Meal : +complexity Complexity
Meal o-- Complexity
Meal : +affordability Affordability
Meal o-- Affordability
Meal : +isGlutenFree bool
Meal : +isLactoseFree bool
Meal : +isVegan bool
Meal : +isVegetarian bool

class Complexity
<<enumeration>> Complexity
Complexity : +index int
Complexity : +values$ List~Complexity~
Complexity : +simple$ Complexity
Complexity o-- Complexity
Complexity : +challenging$ Complexity
Complexity o-- Complexity
Complexity : +hard$ Complexity
Complexity o-- Complexity
Enum <|.. Complexity

class Affordability
<<enumeration>> Affordability
Affordability : +index int
Affordability : +values$ List~Affordability~
Affordability : +affordable$ Affordability
Affordability o-- Affordability
Affordability : +pricey$ Affordability
Affordability o-- Affordability
Affordability : +luxurious$ Affordability
Affordability o-- Affordability
Enum <|.. Affordability

class ReviewedNotifier
StateNotifier <|-- ReviewedNotifier

class Rating
<<enumeration>> Rating
Rating : +index int
Rating : +values$ List~Rating~
Rating : +poor$ Rating
Rating o-- Rating
Enum <|.. Rating

class FavouritesNotifier
FavouritesNotifier : +toggleMealFavouriteStatus() bool
StateNotifier <|-- FavouritesNotifier

class FiltersNotifier
FiltersNotifier : +setFilter() void
FiltersNotifier : +setFilters() void
StateNotifier <|-- FiltersNotifier

class Filter
<<enumeration>> Filter
Filter : +index int
Filter : +values$ List~Filter~
Filter : +glutenFree$ Filter
Filter o-- Filter
Filter : +lactoseFree$ Filter
Filter o-- Filter
Filter : +vegetarian$ Filter
Filter o-- Filter
Filter : +vegan$ Filter
Filter o-- Filter
Enum <|.. Filter

class CategoriesScreen
CategoriesScreen : +availableMeals List~Meal~
CategoriesScreen : +createState() State<CategoriesScreen>
StatefulWidget <|-- CategoriesScreen

class _CategoriesScreenState
_CategoriesScreenState : -_animationController AnimationController
_CategoriesScreenState o-- AnimationController
_CategoriesScreenState : +initState() void
_CategoriesScreenState : +dispose() void
_CategoriesScreenState : -_selectCategory() void
_CategoriesScreenState : +build() Widget
State <|-- _CategoriesScreenState
SingleTickerProviderStateMixin <|-- _CategoriesScreenState

class FiltersScreen
FiltersScreen : +build() Widget
ConsumerWidget <|-- FiltersScreen

class FilterSwitchListTile
FilterSwitchListTile : +title String
FilterSwitchListTile : +subtitle String
FilterSwitchListTile : +filter Filter
FilterSwitchListTile o-- Filter
FilterSwitchListTile : +build() Widget
ConsumerWidget <|-- FilterSwitchListTile

class MealDetailScreen
MealDetailScreen : +meal Meal
MealDetailScreen o-- Meal
MealDetailScreen : +showSnackBar() void
MealDetailScreen : +build() Widget
ConsumerWidget <|-- MealDetailScreen

class AddReviewPopup
AddReviewPopup : +meal Meal
AddReviewPopup o-- Meal
AddReviewPopup : +build() Widget
ConsumerWidget <|-- AddReviewPopup

class MealsScreen
MealsScreen : +title String?
MealsScreen : +meals List~Meal~
MealsScreen : -_showMealScreen() void
MealsScreen : +build() Widget
StatelessWidget <|-- MealsScreen

class ReviewedScreen
ReviewedScreen : +build() Widget
ConsumerWidget <|-- ReviewedScreen

class MealReview
MealReview : +meal Meal
MealReview o-- Meal
MealReview : +rating Rating
MealReview o-- Rating
MealReview : +build() Widget
ConsumerWidget <|-- MealReview

class TabsScreen
TabsScreen : +createState() ConsumerState<TabsScreen>
ConsumerStatefulWidget <|-- TabsScreen

class _TabsScreenState
_TabsScreenState : -_selectedPageIndex int
_TabsScreenState : -_selectPage() void
_TabsScreenState : -_setScreen() void
_TabsScreenState : +build() Widget
ConsumerState <|-- _TabsScreenState

class CategoryGridItem
CategoryGridItem : +category Category
CategoryGridItem o-- Category
CategoryGridItem : +onSelectCategory void Function
CategoryGridItem o-- void Function
CategoryGridItem : +build() Widget
StatelessWidget <|-- CategoryGridItem

class MainDrawer
MainDrawer : +onSelectScreen dynamic FunctionString
MainDrawer o-- dynamic FunctionString
MainDrawer : +build() Widget
MainDrawer : +buildListTile() ListTile
StatelessWidget <|-- MainDrawer

class MealItem
MealItem : +meal Meal
MealItem o-- Meal
MealItem : +onMealItemTap dynamic Function
MealItem o-- dynamic Function
MealItem : +complexityText String
MealItem : +affordabilityText String
MealItem : +build() Widget
StatelessWidget <|-- MealItem

class MealItemTrait
MealItemTrait : +icon IconData
MealItemTrait o-- IconData
MealItemTrait : +label String
MealItemTrait : +build() Widget
StatelessWidget <|-- MealItemTrait
